[package]
name = "rust_lisp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_lisp"
path = "src/main.rs"

[lib]
name = "lisplib"
path = "lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"